CREATE TABLE Employees (
    employee_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR2(200) NOT NULL,
    email VARCHAR2(200) UNIQUE NOT NULL,
    position VARCHAR2(150),
    department_id NUMBER,
    CONSTRAINT FK_Employees_Departments 
        FOREIGN KEY (department_id) REFERENCES Departments(department_id)
);

CREATE TABLE Departments (
    department_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_name VARCHAR2(200) NOT NULL
);



SELECT * FROM Departments;

ALTER TABLE Departments ADD parent_id NUMBER;

ALTER TABLE Departments 
ADD CONSTRAINT FK_Departments_Parent 
FOREIGN KEY (parent_id) REFERENCES Departments(department_id);

CREATE INDEX idx_departments_parent ON Departments(parent_id);




DELETE FROM Departments;

INSERT INTO Departments (department_id, department_name, parent_id) 
VALUES (1, 'TOP MANAGEMENT', NULL);

INSERT INTO Departments (department_id, department_name, parent_id) 
VALUES (2, 'TECH TEAM', NULL);

INSERT INTO Departments (department_id, department_name, parent_id) 
VALUES (3, 'DOCUMENTATION TEAM', NULL);

INSERT INTO Departments (department_id, department_name, parent_id) 
VALUES (4, 'SUPPORT TEAM', NULL);

-- 1. TOP MANAGEMENT (parent_id = 1)
INSERT INTO Departments (department_id, department_name, parent_id) 
VALUES (5, 'Director', 1);

INSERT INTO Departments (department_id, department_name, parent_id) 
VALUES (6, 'Deputy Director', 1);

INSERT INTO Departments (department_id, department_name, parent_id) 
VALUES (7, 'Project Manager', 1);

-- 2. TECH TEAM (parent_id = 2)
INSERT INTO Departments (department_id, department_name, parent_id) 
VALUES (8, 'Architects', 2);

INSERT INTO Departments (department_id, department_name, parent_id) 
VALUES (9, 'Engineers', 2);

-- 3. DOCUMENTATION TEAM (parent_id = 3)
INSERT INTO Departments (department_id, department_name, parent_id) 
VALUES (10, 'Technical Designers', 3);

INSERT INTO Departments (department_id, department_name, parent_id) 
VALUES (11, 'Estimators', 3);

-- 4. SUPPORT TEAM (parent_id = 4)
INSERT INTO Departments (department_id, department_name, parent_id) 
VALUES (12, 'IT Team', 4);

INSERT INTO Departments (department_id, department_name, parent_id) 
VALUES (13, 'HR Team', 4);

INSERT INTO Departments (department_id, department_name, parent_id) 
VALUES (14, 'Marketing Team', 4);



-- Задание 2: Отображение всех подчиненных узлов
CREATE OR REPLACE PROCEDURE sp_ShowSubtree (
    p_parent_id IN NUMBER
) IS
BEGIN
    FOR rec IN (
        SELECT 
            department_name,
            LEVEL AS level_num
        FROM Departments
            START WITH department_id = p_parent_id
            CONNECT BY PRIOR department_id = parent_id
            ORDER BY LEVEL, department_name
    ) LOOP
        DBMS_OUTPUT.PUT_LINE(
            RPAD(LPAD(' ', rec.level_num * 2) || rec.department_name, 30) || 
            ' | Уровень: ' || rec.level_num
        );
    END LOOP;
END sp_ShowSubtree;

EXEC sp_ShowSubtree(1);



-- Задание 3: Добавление подчиненного узла
CREATE OR REPLACE PROCEDURE sp_AddChildNode (
    p_parent_id IN NUMBER,
    p_department_name IN VARCHAR2
) IS
BEGIN
    INSERT INTO Departments (department_id, department_name, parent_id)
    VALUES (
        (SELECT NVL(MAX(department_id), 0) + 1 FROM Departments),
        p_department_name,
        p_parent_id
    );
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Добавлен: ' || p_department_name);
END sp_AddChildNode;

EXEC sp_AddChildNode(2, 'QA Team');
EXEC sp_ShowSubtree(2);
EXEC sp_AddChildNode(8, 'Senior Architects');
EXEC sp_ShowSubtree(2);



--Задание 4: Перемещение подчиненной ветки
CREATE OR REPLACE PROCEDURE sp_MoveSubtree (
    p_source_id IN NUMBER,
    p_target_id IN NUMBER
) IS
BEGIN
    UPDATE Departments 
        SET parent_id = p_target_id
        WHERE department_id = p_source_id;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Перемещено');
END sp_MoveSubtree;
/

EXEC sp_ShowSubtree(2);
EXEC sp_MoveSubtree(15, 3); 
EXEC sp_ShowSubtree(3);

EXEC sp_ShowSubtree(1);
EXEC sp_MoveSubtree(12, 2); 
EXEC sp_ShowSubtree(1);
