SELECT * FROM Vendors;
SELECT * FROM Departments;
SELECT * FROM Software;
SELECT * FROM Licenses;
SELECT * FROM Employees;
SELECT * FROM LicenseAssignments;
SELECT * FROM Requests;
SELECT * FROM Reports;


CREATE TABLE Vendors (
    vendor_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_name VARCHAR2(200) NOT NULL,
    contact_email VARCHAR2(200),
    phone VARCHAR2(50)
);

CREATE TABLE Departments (
    department_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_name VARCHAR2(200) NOT NULL
);

CREATE TABLE Software (
    software_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(200) NOT NULL,
    version VARCHAR2(100),
    category VARCHAR2(100),
    vendor_id NUMBER,
    CONSTRAINT FK_Software_Vendors 
        FOREIGN KEY (vendor_id) REFERENCES Vendors(vendor_id)
);

CREATE TABLE Licenses (
    license_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    software_id NUMBER NOT NULL,
    license_key VARCHAR2(255) UNIQUE NOT NULL,
    license_type VARCHAR2(100),
    purchase_date DATE,
    expiration_date DATE,
    total_seats NUMBER NOT NULL,
    used_seats NUMBER DEFAULT 0, -- денормализация
    cost NUMBER(12,2),
    CONSTRAINT FK_Licenses_Software 
        FOREIGN KEY (software_id) REFERENCES Software(software_id)
);

CREATE TABLE Employees (
    employee_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR2(200) NOT NULL,
    email VARCHAR2(200) UNIQUE NOT NULL,
    position VARCHAR2(150),
    department_id NUMBER,
    CONSTRAINT FK_Employees_Departments 
        FOREIGN KEY (department_id) REFERENCES Departments(department_id)
);

CREATE TABLE LicenseAssignments (
    assignment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    license_id NUMBER NOT NULL,
    employee_id NUMBER NOT NULL,
    assigned_date DATE NOT NULL,
    status VARCHAR2(50),
    device_type VARCHAR2(100),
    device_name VARCHAR2(100),
    CONSTRAINT FK_Assignments_Licenses 
        FOREIGN KEY (license_id) REFERENCES Licenses(license_id),
    CONSTRAINT FK_Assignments_Employees 
        FOREIGN KEY (employee_id) REFERENCES Employees(employee_id)
);

CREATE TABLE Requests (
    request_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id NUMBER NOT NULL,
    software_id NUMBER NOT NULL,
    request_date DATE NOT NULL,
    status VARCHAR2(50),
    CONSTRAINT FK_Requests_Employees 
        FOREIGN KEY (employee_id) REFERENCES Employees(employee_id),
    CONSTRAINT FK_Requests_Software 
        FOREIGN KEY (software_id) REFERENCES Software(software_id)
);

CREATE TABLE Reports (
    report_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_type VARCHAR2(100),
    created_at DATE DEFAULT SYSDATE,
    generated_by NUMBER,
    CONSTRAINT FK_Reports_Employees 
        FOREIGN KEY (generated_by) REFERENCES Employees(employee_id)
);

DROP TABLE LicenseAssignments CASCADE CONSTRAINTS;
DROP TABLE Requests CASCADE CONSTRAINTS;
DROP TABLE Reports CASCADE CONSTRAINTS;
DROP TABLE Licenses CASCADE CONSTRAINTS;
DROP TABLE Employees CASCADE CONSTRAINTS;
DROP TABLE Software CASCADE CONSTRAINTS;
DROP TABLE Vendors CASCADE CONSTRAINTS;
DROP TABLE Departments CASCADE CONSTRAINTS;