worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile      on;
    keepalive_timeout  65;

    server {
        listen       20000;
        server_name  localhost;
        charset      utf-8;

        # TDWA01-01
        location /api/Save-JSON {
            proxy_pass         http://127.0.0.1:40000/NGINX-test;
            proxy_http_version 1.1;
            proxy_set_header   Host $host;
        }

        # TDWA02-01 и TDW02-02
        location / {
            root   C:/General/BELSTU/4k1s/STSR4-1/lab02/www;
            index  TDWA02-01.html;
        }
    }

    server {
        listen       80;
        server_name  localhost;

        location / {
            root   html;
            index  index.html index.htm;
        }
    }
}

#http://localhost:20000/TDWA02-01.html
#http://localhost:20000/TDW02-02.html
