   --1
SELECT PDB_ID, PDB_NAME, STATUS
FROM CDB_PDBS;

--2
ALTER SESSION SET CONTAINER=CDB$ROOT;

CREATE PLUGGABLE DATABASE UVR_PDB
ADMIN USER aesadmin IDENTIFIED BY 12345
ROLES=(CONNECT, RESOURCE)
FILE_NAME_CONVERT = ('C:\Orcl\oradata\ORCL\pdbseed\', 'C:\Orcl\oradata\ORCL\orclpdb\UVR_PDB\');

--3
SELECT PDB_ID, PDB_NAME, STATUS
FROM CDB_PDBS;

--4 
CREATE TABLESPACE TS_UVR_PDB 
    DATAFILE 'C:\Oracacle\oradata\TS_UVR_PDB.dbf' 
    SIZE 100M 
    AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;

CREATE ROLE C##RL_UVR_PDB;
GRANT CREATE SESSION,
    CREATE TABLE,
    CREATE VIEW,
    CREATE PROCEDURE
    TO C##RL_UVR_PDB;

CREATE PROFILE C##PF_UVR_PDB LIMIT 
    SESSIONS_PER_USER 5 
    FAILED_LOGIN_ATTEMPTS 3 
    PASSWORD_LIFE_TIME 30;

CREATE USER C##U1_UVR_PDB IDENTIFIED BY Ugorenko
    DEFAULT TABLESPACE TS_UVR_PDB
    TEMPORARY TABLESPACE TEMP
    PROFILE C##PF_UVR_PDB;

--5 
ALTER USER C##U1_UVR_PDB QUOTA 100M ON TS_UVR_PDB;

CREATE TABLE UVR_TABLE (
    id NUMBER PRIMARY KEY,
    name VARCHAR2(100)
);

INSERT INTO UVR_TABLE (id, name) VALUES (1, 'Item1');
INSERT INTO UVR_TABLE (id, name) VALUES (2, 'Item2');
INSERT INTO UVR_TABLE (id, name) VALUES (3, 'Item3');

SELECT * FROM UVR_TABLE;

--6
SELECT TABLESPACE_NAME, STATUS, CONTENTS FROM DBA_TABLESPACES;

SELECT FILE_NAME, TABLESPACE_NAME, BYTES, MAXBYTES 
FROM DBA_DATA_FILES;

SELECT FILE_NAME, TABLESPACE_NAME, BYTES, MAXBYTES 
FROM DBA_TEMP_FILES;

SELECT ROLE FROM DBA_ROLES;

SELECT GRANTEE, PRIVILEGE, TABLE_NAME
FROM DBA_TAB_PRIVS
WHERE GRANTEE IN (SELECT ROLE FROM DBA_ROLES);

SELECT PROFILE, RESOURCE_NAME, LIMIT FROM DBA_PROFILES;

SELECT USERNAME, ACCOUNT_STATUS FROM DBA_USERS;
SELECT GRANTEE FROM DBA_ROLE_PRIVS;

--7
CREATE USER C##UVR_CORE IDENTIFIED BY Ugorenko;
GRANT CONNECT, RESOURCE TO C##UVR_CORE;

ALTER SESSION SET CONTAINER = UVR_PDB;
GRANT CONNECT TO C##UVR_CORE;
GRANT RESTRICTED SESSION TO C##UVR_CORE;

--8
GRANT CREATE TABLE TO C##UVR_CORE;

--10
ALTER USER C##UVR_CORE QUOTA 100M ON USERS;

CREATE TABLE UVR_TABLE2 (
    id NUMBER PRIMARY KEY,
    name VARCHAR2(100)
);

INSERT INTO UVR_TABLE2 (id, name) VALUES (10, 'Item10');
INSERT INTO UVR_TABLE2 (id, name) VALUES (20, 'Item20');
INSERT INTO UVR_TABLE2 (id, name) VALUES (30, 'Item30');

SELECT * FROM UVR_TABLE2;

--11
SELECT owner, object_name, object_type
FROM dba_objects
WHERE owner = 'C##UVR_CORE';

SELECT owner, object_name, object_type
FROM dba_objects
WHERE owner = 'C##U1_UVR_PDB';

--12
CREATE USER C##DUS IDENTIFIED BY naomi;
GRANT CONNECT, RESOURCE TO C##DUS;
GRANT RESTRICTED SESSION TO C##DUS;

--13
SELECT USER FROM dual;
SELECT USERNAME FROM ALL_USERS;

GRANT SELECT ON V_$SESSION TO SYS;
ALTER SESSION SET CONTAINER = UVR_PDB;
SELECT * FROM ALL_VIEWS WHERE VIEW_NAME = 'V$SESSION';
SELECT * FROM V$SESSION;

CONNECT С##UVR_CORE/Ugorenko AS SYSDBA;

SELECT SID, SERIAL#, USERNAME, OSUSER, MACHINE, PROGRAM, LOGON_TIME
FROM V$SESSION 
WHERE CON_ID = 1;


GRANT SELECT ON UVR_TABLE TO C##DUS;


select * from TEST2;
